service: serverless-flask-github-2-slack

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-east-1
  apiGateway:
    shouldStartNameWithService: true
  memorySize: 128
  logRetentionInDays: 7
  environment:
    # set correct secret on the AWS Lambda console
    GITHUB_SECRET: 123
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 3

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
  github:
    handler: wsgi_handler.handler
    events:
      - http: POST /github

package:
  exclude:
    - .git/**
    - .pytest_cache/**
    - .idea/**